#https://github.com/llvm/clangd-www/blob/main/faq.md
CompileFlags:
  # Add: [-xc++, -std=c++20, -Wall, -Wno-missing-prototypes]
  Add: [-xc++, -std=c++20, -Wall, -Wno-missing-prototypes, -Wextra, -Wshadow, -Wconversion, -Wsign-conversion, -Wunused-parameter, -Wno-long-long, -pedantic]
  # Remove extra warnings specified in compile commands.
  # Single value is also acceptable, same as "Remove: [-mabi]"
  Remove: -mabi
Diagnostics:
  # Tweak Clang-Tidy checks.
  ClangTidy:
    Add: [performance*, modernize*, readability*]
    Remove: [modernize-use-trailing-return-type]
    CheckOptions:
      readability-identifier-naming.VariableCase: CamelCase
